### PR TITLE
Adding in Optimizely for A/B Testing

### PR DESCRIPTION
**Pull request by irobot12729**
Adding in Optimizely so we can do A/B Testing for the landing page.

### CODE REVIEW

**Comment by adrianonco** [comment]
@irobot12729 this said me "Merge with caution" "Waiting to hear about fb594df - The Travis CI build is in progress"

**Comment by irobot12729** [comment]
Yes, I'm seeing it too. I'm not sure why though, I do know that this also popped up when I did the Segment PR. Is there any dev that could check this out?

**Comment by irobot12729** [comment]
@adrianonco Nvm, looks like it was just a matter of time

**Comment by adrianonco** [comment]
Oh yes, only a matter of time, as you say ;)

Merging ;)

**Pull request merged**
