### PR TITLE
Replacing Google Analytics with Segment.

### PR DESCRIPTION
**Pull request by irobot12729**
Deleting the GA code and replacing it with Segment so there's not two streams of data coming in.

### CODE REVIEW

**Comment by adrianonco** [comment]
Great @irobot12729 let me know if I can merge (if you're totally sure is ok) or you need any dev to revise it ;)

Thanksdude!

**Comment by irobot12729** [comment]
This should be fine to merge now, it's just a base for what data we're planning to track

**Comment by kenrick** [comment]
Looks good :shipit:

**Comment by adrianonco** [comment]
Great team!! :)))

**Pull request merged**
